name: nasa_apod_flutter
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  transparent_image: ^1.0.0
  dio: ^3.0.3
  built_value:
  intl: ^0.16.0
  provider: ^3.1.0
  dio_http_cache: ^0.2.0
  cached_network_image: ^2.0.0-rc
  photo_view: ^0.5.0
  image_downloader: ^0.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  built_value_generator:


flutter:
  uses-material-design: true
  assets:
  - assets/
  - assets/images/
